#!/usr/bin/env python3
"""
MAP to KrillClaw Compiler
Converts MAP workflow to KrillClaw-compatible Zig code
"""

import yaml
from pathlib import Path
from typing import Dict, Any, List


class KrillClawCompiler:
    """Compiles MAP workflows to KrillClaw Zig code"""
    
    def __init__(self, workflow: Dict[str, Any]):
        self.workflow = workflow
        self.indent = "    "
        
    def compile(self, output_file: str) -> None:
        """Generate KrillClaw-compatible Zig code"""
        zig_code = self._generate_zig()
        Path(output_file).write_text(zig_code)
        print(f"✅ KrillClaw code generated at: {output_file}")
    
    def _generate_zig(self) -> str:
        """Generate Zig code for KrillClaw"""
        name = self.workflow.get('name', 'unnamed')
        
        code = f"""// Auto-generated by MAP Compiler
// Source: {name}.map.yaml
// Target: KrillClaw Runtime

const std = @import("std");

// Workflow metadata
const WORKFLOW_NAME = "{name}";
const WORKFLOW_VERSION = "{self.workflow.get('version', '1.0')}";

// Step definitions
const Step = struct {{
    id: []const u8,
    intent: []const u8,
    output: ?[]const u8,
}};

// Tool definitions
"""
        
        # Generate tool constants
        tools = self.workflow.get('tools', {})
        for tool_name, tool_config in tools.items():
            tool_type = tool_config.get('type', 'unknown')
            code += f'const TOOL_{tool_name.upper()}: []const u8 = "{tool_type}";\n'
        
        code += """
// Main workflow
pub fn main() !void {
    // Initialize allocator
    var gpa = std.heap.GeneralPurposeAllocator(.{}){{}};
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();
    
    std.log.info("Starting workflow: {s}", .{{WORKFLOW_NAME}});
    
"""
        
        # Generate step execution
        for step in self.workflow.get('steps', []):
            if 'parallel' in step:
                code += self._generate_parallel_steps(step['parallel'])
            else:
                code += self._generate_step_code(step)
        
        code += """
    std.log.info("Workflow completed: {s}", .{WORKFLOW_NAME});
}

"""
        
        # Add helper functions
        code += self._generate_helpers()
        
        return code
    
    def _generate_step_code(self, step: Dict[str, Any], indent_level: int = 1) -> str:
        """Generate code for a single step"""
        ind = self.indent * indent_level
        step_id = step.get('id', 'unnamed')
        intent = step.get('intent', '')
        when = step.get('when')
        
        code = f"{ind}// Step: {step_id}\n"
        code += f'{ind}std.log.info("Executing step: {step_id}", .{{}});\n'
        
        if when:
            code += f"{ind}// Condition: {when}\n"
            code += f"{ind}if (evaluate_condition(\"{when}\")) {{\n"
            code += f'{ind}    std.log.info("Condition met, executing", .{{}});\n'
            code += f"{ind}    // Intent: {intent}\n"
            code += f"{ind}}}\n"
        else:
            code += f"{ind}// Intent: {intent}\n"
        
        code += "\n"
        return code
    
    def _generate_parallel_steps(self, steps: List[Dict[str, Any]]) -> str:
        """Generate code for parallel steps"""
        code = f"{self.indent}// Parallel execution\n"
        code += f"{self.indent}// Note: KrillClaw executes sequentially in this generated code\n"
        code += f"{self.indent}// For true parallelism, use async/await in KrillClaw\n\n"
        
        for step in steps:
            code += self._generate_step_code(step, indent_level=1)
        
        return code
    
    def _generate_helpers(self) -> str:
        """Generate helper functions"""
        return """
// Helper: Evaluate condition (stub)
fn evaluate_condition(condition: []const u8) bool {
    // In production, implement safe condition evaluation
    // For now, return true
    _ = condition;
    return true;
}

// Helper: Execute intent (calls LLM via KrillClaw)
fn execute_intent(intent: []const u8, tools: []const []const u8) ![]const u8 {
    // This would be implemented by KrillClaw's runtime
    // KrillClaw handles LLM calls internally
    _ = tools;
    return intent;
}
"""


def compile_to_krillclaw(map_path: str, output_file: str) -> None:
    """Compile MAP workflow to KrillClaw Zig code"""
    with open(map_path) as f:
        workflow = yaml.safe_load(f)
    
    compiler = KrillClawCompiler(workflow)
    compiler.compile(output_file)


if __name__ == '__main__':
    import sys
    
    if len(sys.argv) < 3:
        print("Usage: python map_to_krillclaw.py <workflow.map.yaml> <output.zig>")
        sys.exit(1)
    
    compile_to_krillclaw(sys.argv[1], sys.argv[2])
